#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FuzzingLocalBot - Reporter Module
Generates professional reports in Markdown, HTML, and JSON.
"""

from datetime import datetime
import json
import os


class Reporter:
    """Generates reports from Analyzer results."""

    def __init__(self, target, analyzer):
        self.target = target
        self.analyzer = analyzer
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # ============================================================
    # MARKDOWN
    # ============================================================
    def generate_markdown(self, total_urls=0, duration=0):
        summary = self.analyzer.get_summary()
        findings = self.analyzer.get_findings()

        report = f"""# 🔍 FuzzingLocalBot - Security Assessment Report

**Target:** `{self.target}`  
**Date:** {self.timestamp}  
**Tool:** FuzzingLocalBot v2.2  

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| URLs tested | {total_urls} |
| Duration | {duration:.1f}s |
| 🔴 Critical | {summary['critical']} |
| 🟠 High | {summary['high']} |
| 🟡 Medium | {summary['medium']} |
| 🔵 Low | {summary['low']} |
| ⚪ Info | {summary['info']} |

---

## 🛠️ Technologies Detected

{chr(10).join(['- ' + tech for tech in summary['technologies']]) if summary['technologies'] else 'No technologies detected.'}

---

"""

        if findings["critical"]:
            report += "## 🔴 Critical Findings\n\n"
            for f in findings["critical"]:
                report += f"### {f['url']}\n"
                report += f"**Status:** {f['status']} | **Length:** {f['content_length']} bytes\n\n"
                for finding in f["findings"]:
                    report += f"- {finding}\n"
                report += "\n"

        if findings["high"]:
            report += "## 🟠 High Findings\n\n"
            for f in findings["high"]:
                report += f"### {f['url']}\n"
                report += f"**Status:** {f['status']} | **Length:** {f['content_length']} bytes\n\n"
                for finding in f["findings"]:
                    report += f"- {finding}\n"
                report += "\n"

        if findings["medium"]:
            report += "## 🟡 Medium Findings\n\n"
            for f in findings["medium"]:
                report += f"- **[{f['status']}]** {f['url']}\n"
                for finding in f["findings"]:
                    report += f"  - {finding}\n"
                report += "\n"

        if findings["low"]:
            report += "## 🔵 Low Findings\n\n"
            for f in findings["low"][:20]:
                report += f"- **[{f['status']}]** {f['url']}\n"
            if len(findings["low"]) > 20:
                report += f"\n*... and {len(findings['low']) - 20} more.*\n"

        report += """---

## 💡 Recommendations

"""
        if summary["critical"] > 0:
            report += "- **URGENT:** Address critical findings immediately.\n"
        if summary["high"] > 0:
            report += "- Review and fix high severity issues.\n"
        report += "- Disable directory listing on all servers.\n"
        report += "- Remove backup and configuration files from public access.\n"
        report += "- Hide server version information.\n"

        report += f"""

---

*Report generated by FuzzingLocalBot v2.2 on {self.timestamp}*
"""

        return report

    def save_markdown(self, total_urls=0, duration=0, output_dir="output"):
        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.md"
        filepath = os.path.join(output_dir, filename)
        report = self.generate_markdown(total_urls, duration)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        return filepath

    # ============================================================
    # HTML PROFESIONAL
    # ============================================================
    def generate_html(self, total_urls=0, duration=0):
        summary = self.analyzer.get_summary()
        findings = self.analyzer.get_findings()

        # Construir filas de hallazgos
        critical_rows = ""
        for f in findings["critical"]:
            critical_rows += f"""
                <tr class="critical">
                    <td><a href="{f['url']}" target="_blank">{f['url']}</a></td>
                    <td>{f['status']}</td>
                    <td>{', '.join(f['findings'])}</td>
                    <td>{f['content_length']} B</td>
                </tr>"""

        high_rows = ""
        for f in findings["high"]:
            high_rows += f"""
                <tr class="high">
                    <td><a href="{f['url']}" target="_blank">{f['url']}</a></td>
                    <td>{f['status']}</td>
                    <td>{', '.join(f['findings'])}</td>
                    <td>{f['content_length']} B</td>
                </tr>"""

        medium_rows = ""
        for f in findings["medium"]:
            medium_rows += f"""
                <tr class="medium">
                    <td><a href="{f['url']}" target="_blank">{f['url']}</a></td>
                    <td>{f['status']}</td>
                    <td>{', '.join(f['findings'])}</td>
                    <td>{f['content_length']} B</td>
                </tr>"""

        # Tecnologías
        tech_list = ""
        for tech in summary.get("technologies", []):
            tech_list += f'<span class="tag">{tech}</span>\n'

        if not tech_list:
            tech_list = '<span class="tag">None detected</span>'

        # Recomendaciones
        recs = ""
        if summary["critical"] > 0:
            recs += '<li><strong>URGENT:</strong> Address critical findings immediately.</li>\n'
        if summary["high"] > 0:
            recs += '<li>Review and fix high severity issues.</li>\n'
        recs += '<li>Disable directory listing on all servers.</li>\n'
        recs += '<li>Remove backup and configuration files from public access.</li>\n'
        recs += '<li>Hide server version information.</li>\n'

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FuzzingLocalBot Report - {self.target}</title>
    <style>
        :root {{
            --bg: #0a0e14;
            --card: #131820;
            --text: #b0b8c4;
            --heading: #e6edf3;
            --critical: #f85149;
            --high: #f0883e;
            --medium: #d29922;
            --low: #58a6ff;
            --info: #8b949e;
            --border: #21262d;
            --accent: #1f6feb;
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 20px;
        }}

        .container {{
            max-width: 1000px;
            margin: 0 auto;
        }}

        .header {{
            text-align: center;
            padding: 40px 20px;
            background: var(--card);
            border-radius: 12px;
            border: 1px solid var(--border);
            margin-bottom: 30px;
        }}

        .header h1 {{
            color: var(--heading);
            font-size: 2em;
            margin-bottom: 10px;
        }}

        .header .target {{
            color: var(--accent);
            font-family: monospace;
            font-size: 1.2em;
        }}

        .header .meta {{
            color: var(--info);
            font-size: 0.9em;
            margin-top: 5px;
        }}

        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
        }}

        .stat-card {{
            background: var(--card);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 20px;
            text-align: center;
        }}

        .stat-card .number {{
            font-size: 2.5em;
            font-weight: bold;
        }}

        .stat-card .label {{
            color: var(--info);
            font-size: 0.85em;
            margin-top: 5px;
            text-transform: uppercase;
        }}

        .stat-card.critical .number {{ color: var(--critical); }}
        .stat-card.high .number {{ color: var(--high); }}
        .stat-card.medium .number {{ color: var(--medium); }}
        .stat-card.low .number {{ color: var(--low); }}
        .stat-card.info .number {{ color: var(--info); }}

        .section {{
            background: var(--card);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 25px;
            margin-bottom: 20px;
        }}

        .section h2 {{
            color: var(--heading);
            font-size: 1.3em;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 1px solid var(--border);
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }}

        th {{
            text-align: left;
            padding: 10px 12px;
            background: var(--bg);
            color: var(--info);
            font-size: 0.85em;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            border-bottom: 1px solid var(--border);
        }}

        td {{
            padding: 10px 12px;
            border-bottom: 1px solid var(--border);
            font-size: 0.9em;
        }}

        tr:hover td {{
            background: rgba(255,255,255,0.02);
        }}

        a {{
            color: var(--accent);
            text-decoration: none;
            font-family: monospace;
            word-break: break-all;
        }}

        a:hover {{ text-decoration: underline; }}

        .tag {{
            display: inline-block;
            background: var(--bg);
            color: var(--accent);
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 0.8em;
            margin: 3px;
            border: 1px solid var(--border);
        }}

        ul {{ padding-left: 20px; }}
        li {{ margin-bottom: 5px; }}

        .footer {{
            text-align: center;
            color: var(--info);
            font-size: 0.85em;
            margin-top: 30px;
            padding: 20px;
        }}

        .no-findings {{
            color: var(--info);
            font-style: italic;
            padding: 20px;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="container">

        <div class="header">
            <h1>🔍 FuzzingLocalBot Report</h1>
            <div class="target">{self.target}</div>
            <div class="meta">{self.timestamp} · {total_urls} URLs · {duration:.1f}s</div>
        </div>

        <div class="summary">
            <div class="stat-card critical">
                <div class="number">{summary['critical']}</div>
                <div class="label">Critical</div>
            </div>
            <div class="stat-card high">
                <div class="number">{summary['high']}</div>
                <div class="label">High</div>
            </div>
            <div class="stat-card medium">
                <div class="number">{summary['medium']}</div>
                <div class="label">Medium</div>
            </div>
            <div class="stat-card low">
                <div class="number">{summary['low']}</div>
                <div class="label">Low</div>
            </div>
            <div class="stat-card info">
                <div class="number">{summary['info']}</div>
                <div class="label">Info</div>
            </div>
        </div>

        <div class="section">
            <h2>🛠️ Technologies Detected</h2>
            {tech_list}
        </div>

        <div class="section">
            <h2>🔴 Critical Findings</h2>
            {f'<table><tr><th>URL</th><th>Status</th><th>Findings</th><th>Size</th></tr>{critical_rows}</table>' if critical_rows else '<div class="no-findings">No critical findings</div>'}
        </div>

        <div class="section">
            <h2>🟠 High Findings</h2>
            {f'<table><tr><th>URL</th><th>Status</th><th>Findings</th><th>Size</th></tr>{high_rows}</table>' if high_rows else '<div class="no-findings">No high findings</div>'}
        </div>

        <div class="section">
            <h2>🟡 Medium Findings</h2>
            {f'<table><tr><th>URL</th><th>Status</th><th>Findings</th><th>Size</th></tr>{medium_rows}</table>' if medium_rows else '<div class="no-findings">No medium findings</div>'}
        </div>

        <div class="section">
            <h2>💡 Recommendations</h2>
            <ul>{recs}</ul>
        </div>

        <div class="footer">
            Generated by FuzzingLocalBot v2.2 on {self.timestamp}
        </div>

    </div>
</body>
</html>"""

        return html

    def save_html(self, total_urls=0, duration=0, output_dir="output"):
        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.html"
        filepath = os.path.join(output_dir, filename)
        html = self.generate_html(total_urls, duration)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)
        return filepath

    # ============================================================
    # JSON ESTRUCTURADO
    # ============================================================
    def generate_json(self, total_urls=0, duration=0):
        summary = self.analyzer.get_summary()
        findings = self.analyzer.get_findings()

        report = {
            "report_metadata": {
                "tool": "FuzzingLocalBot",
                "version": "2.2",
                "target": self.target,
                "date": self.timestamp,
                "urls_tested": total_urls,
                "duration_seconds": round(duration, 1),
            },
            "summary": summary,
            "findings": findings,
        }
        return report

    def save_json(self, total_urls=0, duration=0, output_dir="output"):
        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.json"
        filepath = os.path.join(output_dir, filename)
        data = self.generate_json(total_urls, duration)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return filepath


if __name__ == "__main__":
    print("[*] Reporter module loaded successfully.")
    print("[*] Use: from reporter import Reporter")
