#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FuzzingLocalBot - Reporter Module
Genera informes profesionales en Markdown y HTML.
"""

from datetime import datetime
import os


class Reporter:
    """Genera informes a partir de los resultados del Analyzer."""

    def __init__(self, target, analyzer):
        self.target = target
        self.analyzer = analyzer
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    def generate_markdown(self, total_urls=0, duration=0):
        summary = self.analyzer.get_summary()
        findings = self.analyzer.get_findings()

        report = f"""# FuzzingLocalBot - Security Assessment Report

**Target:** {self.target}  
**Date:** {self.timestamp}  
**Tool:** FuzzingLocalBot v2.0  

---

## Summary

| Metric | Value |
|--------|-------|
| URLs tested | {total_urls} |
| Duration | {duration:.1f}s |
| Critical | {summary['critical']} |
| High | {summary['high']} |
| Medium | {summary['medium']} |
| Low | {summary['low']} |
| Info | {summary['info']} |

---

## Technologies Detected

{chr(10).join(['- ' + tech for tech in summary['technologies']]) if summary['technologies'] else 'No technologies detected.'}

---

"""

        # Critical findings
        if findings["critical"]:
            report += "## Critical Findings\n\n"
            for f in findings["critical"]:
                report += f"### {f['url']}\n"
                report += f"**Status:** {f['status']} | **Length:** {f['content_length']} bytes\n\n"
                for finding in f["findings"]:
                    report += f"- {finding}\n"
                report += "\n"

        # High findings
        if findings["high"]:
            report += "## High Findings\n\n"
            for f in findings["high"]:
                report += f"### {f['url']}\n"
                report += f"**Status:** {f['status']} | **Length:** {f['content_length']} bytes\n\n"
                for finding in f["findings"]:
                    report += f"- {finding}\n"
                report += "\n"

        # Medium findings
        if findings["medium"]:
            report += "## Medium Findings\n\n"
            for f in findings["medium"]:
                report += f"- **[{f['status']}]** {f['url']}\n"
                for finding in f["findings"]:
                    report += f"  - {finding}\n"
                report += "\n"

        # Low findings
        if findings["low"]:
            report += "## Low Findings\n\n"
            for f in findings["low"][:20]:
                report += f"- **[{f['status']}]** {f['url']}\n"
            if len(findings["low"]) > 20:
                report += f"\n*... and {len(findings['low']) - 20} more.*\n"

        # Recommendations
        report += """---

## Recommendations

"""
        if summary["critical"] > 0:
            report += "- **URGENT:** Address critical findings immediately.\n"
        if summary["high"] > 0:
            report += "- Review and fix high severity issues.\n"
        report += "- Disable directory listing on all servers.\n"
        report += "- Remove backup and configuration files from public access.\n"
        report += "- Hide server version information.\n"

        report += f"""

---

*Report generated by FuzzingLocalBot v2.0 on {self.timestamp}*
"""

        return report

    def save_markdown(self, total_urls=0, duration=0, output_dir="output"):
        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.md"
        filepath = os.path.join(output_dir, filename)
        report = self.generate_markdown(total_urls, duration)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        return filepath

    def save_html(self, total_urls=0, duration=0, output_dir="output"):
        md_report = self.generate_markdown(total_urls, duration)

        html_report = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FuzzingLocalBot Report - {self.target}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #0d1117; color: #c9d1d9; }}
        h1 {{ color: #58a6ff; }}
        h2 {{ color: #f0883e; }}
        h3 {{ color: #d2a8ff; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #30363d; padding: 8px; text-align: left; }}
        th {{ background: #161b22; }}
        code {{ background: #161b22; padding: 2px 6px; border-radius: 4px; }}
        pre {{ background: #161b22; padding: 16px; border-radius: 8px; overflow-x: auto; }}
    </style>
</head>
<body>
    <pre>{md_report}</pre>
</body>
</html>"""

        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.html"
        filepath = os.path.join(output_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html_report)

        return filepath


if __name__ == "__main__":
    print("[*] Reporter module loaded successfully.")
    print("[*] Use: from reporter import Reporter")
