#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FuzzingLocalBot Mobile - Reporter Module
Generates TXT reports only (lightweight for Termux).
"""

from datetime import datetime
import os


class Reporter:
    """Generates TXT reports from Analyzer results."""

    def __init__(self, target, analyzer):
        self.target = target
        self.analyzer = analyzer
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    def generate_txt(self, total_urls=0, duration=0):
        summary = self.analyzer.get_summary()
        findings = self.analyzer.get_findings()

        report = f"""============================================================
FuzzingLocalBot Mobile - Security Assessment Report
============================================================

Target: {self.target}
Date: {self.timestamp}
Tool: FuzzingLocalBot Mobile v1.0

============================================================
SUMMARY
============================================================
URLs tested: {total_urls}
Duration: {duration:.1f}s
Critical: {summary['critical']}
High: {summary['high']}
Medium: {summary['medium']}
Low: {summary['low']}
Info: {summary['info']}

============================================================
TECHNOLOGIES DETECTED
============================================================
{chr(10).join(['- ' + tech for tech in summary['technologies']]) if summary['technologies'] else 'None detected.'}

============================================================
CRITICAL FINDINGS
============================================================
"""

        if findings["critical"]:
            for f in findings["critical"]:
                report += f"\nURL: {f['url']}\n"
                report += f"Status: {f['status']}\n"
                for finding in f["findings"]:
                    report += f"  - {finding}\n"
        else:
            report += "None\n"

        report += """
============================================================
HIGH FINDINGS
============================================================
"""
        if findings["high"]:
            for f in findings["high"]:
                report += f"\nURL: {f['url']}\n"
                report += f"Status: {f['status']}\n"
                for finding in f["findings"]:
                    report += f"  - {finding}\n"
        else:
            report += "None\n"

        report += """
============================================================
MEDIUM FINDINGS
============================================================
"""
        if findings["medium"]:
            for f in findings["medium"]:
                report += f"\nURL: {f['url']}\n"
                report += f"Status: {f['status']}\n"
                for finding in f["findings"]:
                    report += f"  - {finding}\n"
        else:
            report += "None\n"

        report += """
============================================================
RECOMMENDATIONS
============================================================
"""
        if summary["critical"] > 0:
            report += "- URGENT: Address critical findings immediately.\n"
        if summary["high"] > 0:
            report += "- Review and fix high severity issues.\n"
        report += "- Disable directory listing on all servers.\n"
        report += "- Remove backup and configuration files from public access.\n"
        report += "- Hide server version information.\n"

        report += f"""
============================================================
Generated by FuzzingLocalBot Mobile v1.0 on {self.timestamp}
============================================================
"""
        return report

    def save_txt(self, total_urls=0, duration=0, output_dir="output"):
        os.makedirs(output_dir, exist_ok=True)
        filename = f"report_{self.target.replace('://', '_').replace('/', '_')}_{self.file_timestamp}.txt"
        filepath = os.path.join(output_dir, filename)
        report = self.generate_txt(total_urls, duration)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        return filepath


if __name__ == "__main__":
    print("[*] Reporter Mobile module loaded successfully.")
    print("[*] Use: from reporter import Reporter")
